### ISSUE TITLE
Assessing access for multiple resources

### ISSUE THREAD

**Issue by jsjohnstone** [ketgo/py-abac#23]
Hi there,

Great module - I've really enjoyed exploring / testing py-abac so far!

I was wondering if @ketgo / anyone had any thoughts on how to deal with assessing access to lists of resources.

For example, given the standard exemplar Pets API (GET /pets, GET /pets/123), is there a solution that might allow you to restrict the list returned by GET /pets to only contain those pets that belong to the user (as opposed to every pet in the database - potentially 100s or 1000s)?

Beyond getting the entire data set (potentially applying some initial filtering logic) and then assessing access to each entry on the list, I wasn't sure if there was more efficient option. 

Any thoughts would be greatly appreciated. 

All the best - Jamie.

**Comment by ketgo** [comment]
Hi @jsjohnstone 

Glad you liked the module!

Regarding your question, you can directly restrict access to the resource-list endpoint using py-ABAC. It is however not designed to perform any filtering operations on the resources. That is for the PEP to perform. In the simple example of the Pets API, you can directly perform a database filter by some user_id in the PEP, i.e your REST API controller. 

If you have a specific use-case in mind then do let me know and I might be able to provide a better response.

Best,
Ketan

**Comment by jsjohnstone** [comment]
Thanks, @ketgo. I'll close this for the time being and come back to you.
