### ISSUE TITLE
Replace `conditions` with `rules`

### ISSUE THREAD

**Issue by sarthakgupta072** [ketgo/py-abac#24]
In the documentation of py-abac, we have `Policy Language` [page] )https://py-abac.readthedocs.io/en/latest/policy_language.html#policy-language) which has this one line

```
A policy composes of uid, description, conditions , targets, effect, and priority fields. The JSON schema is given by
```

It should be `rules` instead of `conditions` , right?

**Comment by ketgo** [comment]
Yes, thanks for fix!
